name: ci

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # 获取源码
    - name: Checkout
      uses: actions/checkout@v2

    # 安装 pnpm
    - name: Cache pnpm modules
      uses: actions/cache@v2 
      with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

    - uses: pnpm/action-setup@v2
      with:
        version: 6.0.2
        run_install: true
    # 安装依赖并打包
    - name: install and build
      run: |
        pnpm install
        pnpm build
    # 自动部署到gh-pages分支
    - name: deploy to gh-pages
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    # 上传到服务器
    - name: deploy to tencent
      uses: easingthemes/ssh-deploy@main
      env:
        # 私钥
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        # scp参数
        ARGS: "-rltgoDzvO --delete"
        # 源目录
        SOURCE: dist/
        # 服务器ip
        REMOTE_HOST: ${{ secrets.SERVER_IP }}
        # 用户
        REMOTE_USER: github
        # 目标地址 你在服务器上部署代码的地方
        TARGET: /data/www/blog
